/**
 * Turn private/guest-list.txt into invite codes and paste-ready SQL.
 *
 *   node scripts/make-guests.mjs
 *
 * Output goes to private/, which is gitignored. This repo is public, and a
 * leaked code lets anyone sign in as that guest — spending their photo quota
 * and reading their bingo answers once review night opens.
 *
 * Re-running is safe: the SQL inserts only names not already in the database,
 * so guests who have already redeemed keep the code on their QR sheet.
 */
import { randomInt } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

// Crockford base32 minus I, L, O and U: no character pairs that get misread
// off a printed card, and no accidental words.
const ALPHABET = '0123456789abcdefghjkmnpqrstvwxyz'
const CODE_LENGTH = 3

const IN = 'private/guest-list.txt'
const OUT_SQL = 'private/insert-guests.sql'
const OUT_CSV = 'private/invite-codes.csv'

const BASE_URL = process.env.WEDD_BASE_URL ?? 'https://wedd-book.jiani-yan.workers.dev'

function newCode(taken) {
  for (let i = 0; i < 10000; i++) {
    let code = ''
    for (let j = 0; j < CODE_LENGTH; j++) code += ALPHABET[randomInt(ALPHABET.length)]
    if (!taken.has(code)) {
      taken.add(code)
      return code
    }
  }
  throw new Error(`Could not find a free ${CODE_LENGTH}-character code — the space is too crowded.`)
}

const names = readFileSync(IN, 'utf8')
  .split('\n')
  .map((l) => l.trim())
  .filter((l) => l && !l.startsWith('#'))
  // "A & B" is two people, each with their own code, quota and bingo card.
  .flatMap((l) => l.split('&').map((n) => n.trim()))
  .filter(Boolean)

const duplicates = names.filter((n, i) => names.indexOf(n) !== i)
if (duplicates.length) {
  console.error(`Duplicate names would collide on insert: ${[...new Set(duplicates)].join(', ')}`)
  process.exit(1)
}

const taken = new Set()
const guests = names.map((name) => ({ name, code: newCode(taken) }))

const sqlEscape = (s) => s.replaceAll("'", "''")

const sql = `-- Generated by scripts/make-guests.mjs — do not commit.
-- Paste into the Supabase SQL Editor (Dashboard → SQL Editor → Run).
--
-- Idempotent on display_name: re-running adds only new people and leaves
-- existing invite codes untouched, so printed QR sheets stay valid.

insert into guests (invite_code, display_name)
select v.code, v.name
  from (values
${guests.map((g) => `    ('${g.code}', '${sqlEscape(g.name)}')`).join(',\n')}
  ) as v(code, name)
 where not exists (select 1 from guests g where g.display_name = v.name);

select display_name, invite_code from guests order by created_at, display_name;
`

const csv = [
  'name,code,url',
  ...guests.map((g) => `"${g.name.replaceAll('"', '""')}",${g.code},${BASE_URL}/?c=${g.code}`),
].join('\n')

mkdirSync('private', { recursive: true })
writeFileSync(OUT_SQL, sql)
writeFileSync(OUT_CSV, csv + '\n')

const width = Math.max(...guests.map((g) => g.name.length))
console.log(`\n${guests.length} guests\n`)
for (const g of guests) {
  console.log(`  ${g.name.padEnd(width)}  ${g.code}   ${BASE_URL}/?c=${g.code}`)
}
console.log(`\nWrote ${OUT_SQL} and ${OUT_CSV} (both gitignored)\n`)
